name: CI

on: [push]
env:
  PKG_MANAGER: yarn

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        yarn test,
        echo test, and deploy your project.
